version: '3.9'

services:
    postgres:
        image: postgres:15.1
        container_name: postgres-15.1
        restart: unless-stopped
        ports:
           - "5432:5432"
        environment:
            POSTGRES_DB: yii2_picsum_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
           - postgres:/var/lib/postgresql/data
        networks:
           app:

    php:
        build: ./images/php
        container_name: php-7.4
        restart: unless-stopped
        depends_on:
            - postgres
        volumes:
           - ./www:/var/www
        networks:
           app:

    nginx:
        image: nginx:1.23.2
        container_name: nginx-1.23.2
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        networks:
           app:

    adminer:
        image: adminer:4.8.1
        container_name: adminer-4.8.1
        ports:
            - "8080:8080"
        networks:
            app:

networks:
    app:
        name: app

volumes:
    postgres:
        name: app_volume_psql
